In [8]:
import pandas as pd
df = pd.read_csv('STEG_BILLING_HISTORY.csv')
client_0_bills = df.head(10)
print(client_0_bills)

<ipython-input-8-4f841087c261>:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('STEG_BILLING_HISTORY.csv')

        client_id invoice_date  tarif_type  counter_number counter_statue  \
0  train_Client_0   2014-03-24          11       1335667.0              0
1  train_Client_0   2013-03-29          11       1335667.0              0
2  train_Client_0   2015-03-23          11       1335667.0              0
3  train_Client_0   2015-07-13          11       1335667.0              0
4  train_Client_0   2016-11-17          11       1335667.0              0
5  train_Client_0   2017-07-17          11       1335667.0              0
6  train_Client_0   2018-12-07          11       1335667.0              0
7  train_Client_0   2019-03-19          11       1335667.0              0
8  train_Client_0   2011-07-22          11       1335667.0              0
9  train_Client_0   2011-11-22          11       1335667.0              0

   counter_code  reading_remarque  counter_coefficient  consommation_level_1  \
0           203               8.0                    1                    82
1           203               6.0                    1                  1200
2           203               8.0                    1                   123
3           207               8.0                    1                   102
4           207               9.0                    1                   572
5           207               9.0                    1                   314
6           207               9.0                    1                   541
7           207               9.0                    1                   585
8           203               9.0                    1                  1200
9           203               6.0                    1                  1082

   consommation_level_2  consommation_level_3  consommation_level_4  \
0                     0                     0                     0
1                   184                     0                     0
2                     0                     0                     0
3                     0                     0                     0
4                     0                     0                     0
5                     0                     0                     0
6                     0                     0                     0
7                     0                     0                     0
8                   186                     0                     0
9                     0                     0                     0

   old_index  new_index  months_number counter_type
0      14302      14384              4         ELEC
1      12294      13678              4         ELEC
2      14624      14747              4         ELEC
3      14747      14849              4         ELEC
4      15066      15638             12         ELEC
5      15638      15952              8         ELEC
6      15952      16493             12         ELEC
7      16493      17078              8         ELEC
8       7770       9156              4         ELEC
9       9156      10238              4         ELEC
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4476749 entries, 0 to 4476748
Data columns (total 16 columns):
 #   Column                Dtype
---  ------                -----
 0   client_id             object
 1   invoice_date          object
 2   tarif_type            int64
 3   counter_number        float64
 4   counter_statue        object
 5   counter_code          int64
 6   reading_remarque      float64
 7   counter_coefficient   int64
 8   consommation_level_1  int64
 9   consommation_level_2  int64
 10  consommation_level_3  int64
 11  consommation_level_4  int64
 12  old_index             int64
 13  new_index             int64
 14  months_number         int64
 15  counter_type          object
dtypes: float64(2), int64(10), object(4)
memory usage: 546.5+ MB
                   client_id invoice_date  tarif_type  counter_number  \
615      train_Client_100012   2010-01-28          11        144686.0
1261     train_Client_100027   2016-05-08          11         21762.0
1301     train_Client_100028   2017-03-24          40        127333.0
2196     train_Client_100060   2014-03-21          11       1177241.0
2366     train_Client_100067   2018-11-15          11        964342.0
...                      ...          ...         ...             ...
4469301   train_Client_99807   2017-08-02          10        561179.0
4470347   train_Client_99832   2013-06-26          11       1242722.0
4470694    train_Client_9984   2013-04-09          11         96557.0
4473803    train_Client_9992   2018-07-26          11          3020.0
4474866   train_Client_99947   2016-09-05          40       6847056.0

        counter_statue  counter_code  reading_remarque  counter_coefficient  \
615                  0           413               NaN                    1
1261                 0           413               NaN                    1
1301                 0             5               NaN                    1
2196                 0           203               NaN                    1
2366                 0           203               NaN                    1
...                ...           ...               ...                  ...
4469301              0           202               NaN                    1
4470347              0           207               NaN                    1
4470694              0           203               NaN                    1
4473803              0           203               NaN                    1
4474866              0             5               NaN                    1

         consommation_level_1  consommation_level_2  consommation_level_3  \
615                       419                     0                     0
1261                      169                     0                     0
1301                      177                     0                     0
2196                      327                     0                     0
2366                      596                     0                     0
...                       ...                   ...                   ...
4469301                   134                     0                     0
4470347                   149                     0                     0
4470694                   707                     0                     0
4473803                  2400                  1200                   161
4474866                   222                     0                     0

         consommation_level_4  old_index  new_index  months_number  \
615                         0       1723       2142             12
1261                        0      17410      17579              4
1301                        0       8849       9026              4
2196                        0       5042       5369              4
2366                        0      35114      35710              4
...                       ...        ...        ...            ...
4469301                     0       9633       9767              4
4470347                     0      43434      43583              2
4470694                     0      65977      66684              4
4473803                     0       1470       5231             12
4474866                     0       6900       7122              4

        counter_type
615             ELEC
1261            ELEC
1301             GAZ
2196            ELEC
2366            ELEC
...              ...
4469301         ELEC
4470347         ELEC
4470694         ELEC
4473803         ELEC
4474866          GAZ

[4579 rows x 16 columns]
                  client_id invoice_date  tarif_type  counter_number  \
0            train_Client_0   2014-03-24          11       1335667.0
1            train_Client_0   2013-03-29          11       1335667.0
2            train_Client_0   2015-03-23          11       1335667.0
3            train_Client_0   2015-07-13          11       1335667.0
4            train_Client_0   2016-11-17          11       1335667.0
...                     ...          ...         ...             ...
4476744  train_Client_99998   2005-08-19          10       1253571.0
4476745  train_Client_99998   2005-12-19          10       1253571.0
4476746  train_Client_99999   1996-09-25          11        560948.0
4476747  train_Client_99999   1996-05-28          11        560948.0
4476748  train_Client_99999   1996-01-25          11        560948.0

        counter_statue  counter_code  reading_remarque  counter_coefficient  \
0                    0           203               8.0                    1
1                    0           203               6.0                    1
2                    0           203               8.0                    1
3                    0           207               8.0                    1
4                    0           207               9.0                    1
...                ...           ...               ...                  ...
4476744              0           202               9.0                    1
4476745              0           202               6.0                    1
4476746              0           203               6.0                    1
4476747              0           203               6.0                    1
4476748              0           203               6.0                    1

         consommation_level_1  consommation_level_2  consommation_level_3  \
0                          82                     0                     0
1                        1200                   184                     0
2                         123                     0                     0
3                         102                     0                     0
4                         572                     0                     0
...                       ...                   ...                   ...
4476744                   400                   135                     0
4476745                   200                     6                     0
4476746                   259                     0                     0
4476747                   603                     0                     0
4476748                   516                     0                     0

         consommation_level_4  old_index  new_index  months_number  \
0                           0      14302      14384              4
1                           0      12294      13678              4
2                           0      14624      14747              4
3                           0      14747      14849              4
4                           0      15066      15638             12
...                       ...        ...        ...            ...
4476744                     0       3197       3732              8
4476745                     0       3732       3938              4
4476746                     0      13884      14143              4
4476747                     0      13281      13884              4
4476748                     0      12765      13281              4

        counter_type
0               ELEC
1               ELEC
2               ELEC
3               ELEC
4               ELEC
...              ...
4476744         ELEC
4476745         ELEC
4476746         ELEC
4476747         ELEC
4476748         ELEC

[4472170 rows x 16 columns]

In [ ]:
# 2 What is the data type of the 'client_0_bills' variable ?

print(type(client_0_bills))

In [ ]:
# 3 Infos

df.info()

In [ ]:
# 4 Find missing values
MissingValues = df[df.isnull().any(axis=1)]
print(MissingValues)

In [ ]:
# 5 Handling missing values

df_cleaned = df.dropna()
print(df_cleaned)

In [10]:
# 6 Describe (Mean median ect)

df.describe()

,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number
count,4.476749e+06,4.476701e+06,4.476749e+06,4.472218e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06
mean,2.012804e+01,1.230595e+11,1.724884e+02,7.321713e+00,1.003040e+00,4.109795e+02,1.093225e+02,2.030620e+01,5.292588e+01,1.776700e+04,1.834970e+04,4.483095e+01
std,1.347256e+01,1.657276e+12,1.338871e+02,1.571859e+00,3.083466e-01,7.573080e+02,1.220123e+03,1.574239e+02,8.754725e+02,4.036693e+04,4.095321e+04,3.128335e+03
min,8.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.100000e+01,1.211080e+05,5.000000e+00,6.000000e+00,1.000000e+00,7.900000e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.791000e+03,2.056000e+03,4.000000e+00
50%,1.100000e+01,4.945610e+05,2.030000e+02,8.000000e+00,1.000000e+00,2.740000e+02,0.000000e+00,0.000000e+00,0.000000e+00,7.690000e+03,8.192000e+03,4.000000e+00
75%,4.000000e+01,1.115161e+06,2.070000e+02,9.000000e+00,1.000000e+00,6.000000e+02,0.000000e+00,0.000000e+00,0.000000e+00,2.166000e+04,2.234300e+04,4.000000e+00
max,4.500000e+01,2.798115e+13,6.000000e+02,4.130000e+02,5.000000e+01,9.999100e+05,9.990730e+05,6.449200e+04,5.479460e+05,2.800280e+06,2.870972e+06,6.366240e+05

In [19]:
# Select bills records for client with id 'train_Client_0' using loc
client_0_bills_loc = df.loc[df['client_id'] == 'train_Client_0']
print(client_0_bills_loc)

# Select bills records for client with id 'train_Client_0' using boolean indexing
client_0_bills_bool = df[df['client_id'] == 'train_Client_0']
print(client_0_bills_bool)

         client_id invoice_date  tarif_type  counter_number counter_statue  \
0   train_Client_0   2014-03-24          11       1335667.0              0
1   train_Client_0   2013-03-29          11       1335667.0              0
2   train_Client_0   2015-03-23          11       1335667.0              0
3   train_Client_0   2015-07-13          11       1335667.0              0
4   train_Client_0   2016-11-17          11       1335667.0              0
5   train_Client_0   2017-07-17          11       1335667.0              0
6   train_Client_0   2018-12-07          11       1335667.0              0
7   train_Client_0   2019-03-19          11       1335667.0              0
8   train_Client_0   2011-07-22          11       1335667.0              0
9   train_Client_0   2011-11-22          11       1335667.0              0
10  train_Client_0   2008-11-25          11       1335667.0              0
11  train_Client_0   2012-07-23          11       1335667.0              0
12  train_Client_0   2012-11-29          11       1335667.0              0
13  train_Client_0   2013-07-22          11       1335667.0              0
14  train_Client_0   2014-07-18          11       1335667.0              0
15  train_Client_0   2014-11-24          11       1335667.0              0
16  train_Client_0   2015-11-18          11       1335667.0              0
17  train_Client_0   2012-03-27          11       1335667.0              0
18  train_Client_0   2011-03-30          11       1335667.0              0
19  train_Client_0   2013-02-12          11       1335667.0              0
20  train_Client_0   2010-07-22          11       1335667.0              0
21  train_Client_0   2010-11-24          11       1335667.0              0
22  train_Client_0   2005-10-17          11       1335667.0              0
23  train_Client_0   2006-02-24          11       1335667.0              0
24  train_Client_0   2006-06-23          11       1335667.0              0
25  train_Client_0   2006-10-18          11       1335667.0              0
26  train_Client_0   2007-06-27          11       1335667.0              0
27  train_Client_0   2007-10-25          11       1335667.0              0
28  train_Client_0   2007-02-26          11       1335667.0              0
29  train_Client_0   2008-07-28          11       1335667.0              0
30  train_Client_0   2009-01-04          11       1335667.0              0
31  train_Client_0   2009-07-27          11       1335667.0              0
32  train_Client_0   2009-11-24          11       1335667.0              0
33  train_Client_0   2010-03-29          11       1335667.0              0
34  train_Client_0   2008-01-04          11       1335667.0              0

    counter_code  reading_remarque  counter_coefficient  consommation_level_1  \
0            203               8.0                    1                    82
1            203               6.0                    1                  1200
2            203               8.0                    1                   123
3            207               8.0                    1                   102
4            207               9.0                    1                   572
5            207               9.0                    1                   314
6            207               9.0                    1                   541
7            207               9.0                    1                   585
8            203               9.0                    1                  1200
9            203               6.0                    1                  1082
10           203               6.0                    1                   174
11           203               6.0                    1                   628
12           203               6.0                    1                   886
13           203               8.0                    1                   147
14           203               8.0                    1                    99
15           203               8.0                    1                   141
16           207               9.0                    1                   217
17           203               8.0                    1                   292
18           203               6.0                    1                   497
19           203               8.0                    1                    38
20           203               6.0                    1                   278
21           203               6.0                    1                   234
22           203               6.0                    1                   124
23           203               6.0                    1                   141
24           203               6.0                    1                   162
25           203               6.0                    1                   159
26           203               6.0                    1                   240
27           203               6.0                    1                   276
28           203               6.0                    1                   182
29           203               6.0                    1                   171
30           203               6.0                    1                   315
31           203               6.0                    1                   312
32           203               6.0                    1                   267
33           203               6.0                    1                   276
34           203               6.0                    1                   277

    consommation_level_2  consommation_level_3  consommation_level_4  \
0                      0                     0                     0
1                    184                     0                     0
2                      0                     0                     0
3                      0                     0                     0
4                      0                     0                     0
5                      0                     0                     0
6                      0                     0                     0
7                      0                     0                     0
8                    186                     0                     0
9                      0                     0                     0
10                     0                     0                     0
11                     0                     0                     0
12                     0                     0                     0
13                     0                     0                     0
14                     0                     0                     0
15                     0                     0                     0
16                     0                     0                     0
17                     0                     0                     0
18                     0                     0                     0
19                     0                     0                     0
20                     0                     0                     0
21                     0                     0                     0
22                     0                     0                     0
23                     0                     0                     0
24                     0                     0                     0
25                     0                     0                     0
26                     0                     0                     0
27                     0                     0                     0
28                     0                     0                     0
29                     0                     0                     0
30                     0                     0                     0
31                     0                     0                     0
32                     0                     0                     0
33                     0                     0                     0
34                     0                     0                     0

    old_index  new_index  months_number counter_type
0       14302      14384              4         ELEC
1       12294      13678              4         ELEC
2       14624      14747              4         ELEC
3       14747      14849              4         ELEC
4       15066      15638             12         ELEC
5       15638      15952              8         ELEC
6       15952      16493             12         ELEC
7       16493      17078              8         ELEC
8        7770       9156              4         ELEC
9        9156      10238              4         ELEC
10       5417       5591              4         ELEC
11      10780      11408              4         ELEC
12      11408      12294              4         ELEC
13      13983      14130              4         ELEC
14      14384      14483              4         ELEC
15      14483      14624              4         ELEC
16      14849      15066              4         ELEC
17      10488      10780              4         ELEC
18       7273       7770              4         ELEC
19      14264      14302              2         ELEC
20       6761       7039              4         ELEC
21       7039       7273              4         ELEC
22       3685       3809              4         ELEC
23       3809       3950              4         ELEC
24       3950       4112              4         ELEC
25       4112       4271              4         ELEC
26       4453       4693              4         ELEC
27       4693       4969              4         ELEC
28       4271       4453              4         ELEC
29       5246       5417              4         ELEC
30       5591       5906              4         ELEC
31       5906       6218              4         ELEC
32       6218       6485              4         ELEC
33       6485       6761              4         ELEC
34       4969       5246              4         ELEC
         client_id invoice_date  tarif_type  counter_number counter_statue  \
0   train_Client_0   2014-03-24          11       1335667.0              0
1   train_Client_0   2013-03-29          11       1335667.0              0
2   train_Client_0   2015-03-23          11       1335667.0              0
3   train_Client_0   2015-07-13          11       1335667.0              0
4   train_Client_0   2016-11-17          11       1335667.0              0
5   train_Client_0   2017-07-17          11       1335667.0              0
6   train_Client_0   2018-12-07          11       1335667.0              0
7   train_Client_0   2019-03-19          11       1335667.0              0
8   train_Client_0   2011-07-22          11       1335667.0              0
9   train_Client_0   2011-11-22          11       1335667.0              0
10  train_Client_0   2008-11-25          11       1335667.0              0
11  train_Client_0   2012-07-23          11       1335667.0              0
12  train_Client_0   2012-11-29          11       1335667.0              0
13  train_Client_0   2013-07-22          11       1335667.0              0
14  train_Client_0   2014-07-18          11       1335667.0              0
15  train_Client_0   2014-11-24          11       1335667.0              0
16  train_Client_0   2015-11-18          11       1335667.0              0
17  train_Client_0   2012-03-27          11       1335667.0              0
18  train_Client_0   2011-03-30          11       1335667.0              0
19  train_Client_0   2013-02-12          11       1335667.0              0
20  train_Client_0   2010-07-22          11       1335667.0              0
21  train_Client_0   2010-11-24          11       1335667.0              0
22  train_Client_0   2005-10-17          11       1335667.0              0
23  train_Client_0   2006-02-24          11       1335667.0              0
24  train_Client_0   2006-06-23          11       1335667.0              0
25  train_Client_0   2006-10-18          11       1335667.0              0
26  train_Client_0   2007-06-27          11       1335667.0              0
27  train_Client_0   2007-10-25          11       1335667.0              0
28  train_Client_0   2007-02-26          11       1335667.0              0
29  train_Client_0   2008-07-28          11       1335667.0              0
30  train_Client_0   2009-01-04          11       1335667.0              0
31  train_Client_0   2009-07-27          11       1335667.0              0
32  train_Client_0   2009-11-24          11       1335667.0              0
33  train_Client_0   2010-03-29          11       1335667.0              0
34  train_Client_0   2008-01-04          11       1335667.0              0

    counter_code  reading_remarque  counter_coefficient  consommation_level_1  \
0            203               8.0                    1                    82
1            203               6.0                    1                  1200
2            203               8.0                    1                   123
3            207               8.0                    1                   102
4            207               9.0                    1                   572
5            207               9.0                    1                   314
6            207               9.0                    1                   541
7            207               9.0                    1                   585
8            203               9.0                    1                  1200
9            203               6.0                    1                  1082
10           203               6.0                    1                   174
11           203               6.0                    1                   628
12           203               6.0                    1                   886
13           203               8.0                    1                   147
14           203               8.0                    1                    99
15           203               8.0                    1                   141
16           207               9.0                    1                   217
17           203               8.0                    1                   292
18           203               6.0                    1                   497
19           203               8.0                    1                    38
20           203               6.0                    1                   278
21           203               6.0                    1                   234
22           203               6.0                    1                   124
23           203               6.0                    1                   141
24           203               6.0                    1                   162
25           203               6.0                    1                   159
26           203               6.0                    1                   240
27           203               6.0                    1                   276
28           203               6.0                    1                   182
29           203               6.0                    1                   171
30           203               6.0                    1                   315
31           203               6.0                    1                   312
32           203               6.0                    1                   267
33           203               6.0                    1                   276
34           203               6.0                    1                   277

    consommation_level_2  consommation_level_3  consommation_level_4  \
0                      0                     0                     0
1                    184                     0                     0
2                      0                     0                     0
3                      0                     0                     0
4                      0                     0                     0
5                      0                     0                     0
6                      0                     0                     0
7                      0                     0                     0
8                    186                     0                     0
9                      0                     0                     0
10                     0                     0                     0
11                     0                     0                     0
12                     0                     0                     0
13                     0                     0                     0
14                     0                     0                     0
15                     0                     0                     0
16                     0                     0                     0
17                     0                     0                     0
18                     0                     0                     0
19                     0                     0                     0
20                     0                     0                     0
21                     0                     0                     0
22                     0                     0                     0
23                     0                     0                     0
24                     0                     0                     0
25                     0                     0                     0
26                     0                     0                     0
27                     0                     0                     0
28                     0                     0                     0
29                     0                     0                     0
30                     0                     0                     0
31                     0                     0                     0
32                     0                     0                     0
33                     0                     0                     0
34                     0                     0                     0

    old_index  new_index  months_number counter_type
0       14302      14384              4         ELEC
1       12294      13678              4         ELEC
2       14624      14747              4         ELEC
3       14747      14849              4         ELEC
4       15066      15638             12         ELEC
5       15638      15952              8         ELEC
6       15952      16493             12         ELEC
7       16493      17078              8         ELEC
8        7770       9156              4         ELEC
9        9156      10238              4         ELEC
10       5417       5591              4         ELEC
11      10780      11408              4         ELEC
12      11408      12294              4         ELEC
13      13983      14130              4         ELEC
14      14384      14483              4         ELEC
15      14483      14624              4         ELEC
16      14849      15066              4         ELEC
17      10488      10780              4         ELEC
18       7273       7770              4         ELEC
19      14264      14302              2         ELEC
20       6761       7039              4         ELEC
21       7039       7273              4         ELEC
22       3685       3809              4         ELEC
23       3809       3950              4         ELEC
24       3950       4112              4         ELEC
25       4112       4271              4         ELEC
26       4453       4693              4         ELEC
27       4693       4969              4         ELEC
28       4271       4453              4         ELEC
29       5246       5417              4         ELEC
30       5591       5906              4         ELEC
31       5906       6218              4         ELEC
32       6218       6485              4         ELEC
33       6485       6761              4         ELEC
34       4969       5246              4         ELEC

In [20]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Transform the 'counter_type' feature
df['counter_type_encoded'] = label_encoder.fit_transform(df['counter_type'])

# Display the transformed DataFrame
print(df[['counter_type', 'counter_type_encoded']])

        counter_type  counter_type_encoded
0               ELEC                     0
1               ELEC                     0
2               ELEC                     0
3               ELEC                     0
4               ELEC                     0
...              ...                   ...
4476744         ELEC                     0
4476745         ELEC                     0
4476746         ELEC                     0
4476747         ELEC                     0
4476748         ELEC                     0

[4476749 rows x 2 columns]

In [21]:

df = df.drop(columns=['counter_statue'])

# Display the DataFrame to confirm the column is removed
print(df.head())

        client_id invoice_date  tarif_type  counter_number  counter_code  \
0  train_Client_0   2014-03-24          11       1335667.0           203
1  train_Client_0   2013-03-29          11       1335667.0           203
2  train_Client_0   2015-03-23          11       1335667.0           203
3  train_Client_0   2015-07-13          11       1335667.0           207
4  train_Client_0   2016-11-17          11       1335667.0           207

   reading_remarque  counter_coefficient  consommation_level_1  \
0               8.0                    1                    82
1               6.0                    1                  1200
2               8.0                    1                   123
3               8.0                    1                   102
4               9.0                    1                   572

   consommation_level_2  consommation_level_3  consommation_level_4  \
0                     0                     0                     0
1                   184                     0                     0
2                     0                     0                     0
3                     0                     0                     0
4                     0                     0                     0

   old_index  new_index  months_number counter_type  counter_type_encoded
0      14302      14384              4         ELEC                     0
1      12294      13678              4         ELEC                     0
2      14624      14747              4         ELEC                     0
3      14747      14849              4         ELEC                     0
4      15066      15638             12         ELEC                     0